### PR TITLE
Beautify code with beautifier.io

### PR DESCRIPTION
**Pull request by afkvido**
I processed index.html with https://beautifier.io, it seems better to me now.

EDIT: I also beatified the CSS and JavaScript

### CODE REVIEW

**Review by yeeteeyt — COMMENTED** [review]
great!

**Comment by yeeteeyt** [comment]
could you please commit it yourself? I don't have git currently.

**Comment by afkvido** [comment]
Oh, ok.

**Comment by afkvido** [comment]
Anyways, you beautified it yourself, so there's no need to commit it.

**Pull request closed without merging**
