### PR TITLE
Mozilla Public License 2.0

### PR DESCRIPTION
**Pull request by afkvido**

### CODE REVIEW

**Comment by yeeteeyt** [comment]
ok

**Comment by yeeteeyt** [comment]
I think I did it, right?

**Comment by afkvido** [comment]
> I think I did it, right?

Lmao, it's merge, not close.

**Comment by yeeteeyt** [comment]
so what have you come up with?

**Comment by afkvido** [comment]
> so what have you come up with?

Mozilla Public License 2.0?

It's a license by Mozilla that prevents people from selling your unmodified code.

**Comment by yeeteeyt** [comment]
nice.


well, did you find a bug in the canvas?

**Comment by afkvido** [comment]
Do I need to log in with a google account?

**Comment by yeeteeyt** [comment]
no dude. the site is super broken. what you're supposed to do is help me fix that. the hack works JUST FINE. just help me edit that main canvas part to see wtf is wrong with it.

I know you can help, please try

**Comment by afkvido** [comment]
> no dude. the site is super broken. what you're supposed to do is help me fix that. the hack works JUST FINE. just help me edit that main canvas part to see wtf is wrong with it.
> 
> I know you can help, please try

Oh, ok.

**Comment by afkvido** [comment]
I think an IDE to do this efficiently

**Comment by yeeteeyt** [comment]
ok

**Comment by yeeteeyt** [comment]
did you find something? I updated it again

**Comment by afkvido** [comment]
I think we should process the code in beautifier.io. I'll open a PR, just in case we need to revert the changes.

**Pull request merged**
